### ISSUE TITLE
2023-09-27

### ISSUE THREAD

**Issue by NYCASA** [DylanAlloy/tda-sheets#1]
Time Stamp does not seem to be updating – its when the script starts
Column H currently – needs to be first column so vlookup can happen
lower count and upper count does not seem to be updating
TOTAL_VOLUME does not work for some values, we are getting examples such as 8.45
Volume doesnt seem to be correct

**Comment by mxchinegod** [comment]
Looking into third thing and fourth thing. Fixed first one.

For the second thing: "Column H", can you explain what you mean more? Do you mean what is currently H should be A? I believe it is the symbol right now. 

Thank you.

https://github.com/DylanAlloy/tda-sheets/commit/10870ccafdce40b072a758eeffc19ec7cb61d9d7

**Comment by NYCASA** [comment]
Most def - back at home late tonight - will look into this tomorrow morning
first thing - Thank You!

**Comment by NYCASA** [comment]
Four Items Below – please see below in second item

1 - Time Stamp does not seem to be updating – its when the script starts
Thank You! Fixed

2 - Column H currently – needs to be first column so vlookup can happen
Example SPXW230927C4300 (column h – symbol) if it can be the first column in the Data Worksheet – cant do vlookups if its not that way – due to Google sheets / Excel Limitation 

3 - lower count and upper count does not seem to be updating

4 - TOTAL_VOLUME does not work for some values, we are getting examples such as 8.45 Volume doesn’t seem to be correct

**Comment by mxchinegod** [comment]
2 should be fixed now! Looking into 3, 4. market/weekend things. 

if 2 is not resolved or a bug emerges from the change let me know ASAP!

https://github.com/DylanAlloy/tda-sheets/commit/a251d8bebf64e600f00612b2db8c106e82469631

**Comment by NYCASA** [comment]
Thank You! Can you advise if the code is updated?

**Comment by NYCASA** [comment]
Thank You! getting the error after tda_token.py

PS C:\Users\amananeja\Documents\@ Python\Terminal-TD> & C:/Python311/python.exe "c:/Users/amananeja/Documents/@ Python/Terminal-TD/sheets.py"
49 rows retrieved
49 rows retrieved
49 rows retrieved
Traceback (most recent call last):
  File "c:\Users\amananeja\Documents\@ Python\Terminal-TD\sheets.py", line 158, in <module>
    TDA('REMOVED', REMOVED', inputs, sheet)
  File "c:\Users\amananeja\Documents\@ Python\Terminal-TD\sheets.py", line 14, in TDA
    client = tda.auth.client_from_token_file('./tda_token.json',api_key)
             ^^^^^^^^
AttributeError: 'str' object has no attribute 'auth'

Api Kiey & Account removed

**Comment by mxchinegod** [comment]
I _believe_ this issue should be fixed in https://github.com/DylanAlloy/tda-sheets/commit/b69478e4d606609fa00d1674ffa8b75b7ce0f08a

issue arrises from slightly different `tda-api` versions for python. was working on a diff laptop.

**Comment by NYCASA** [comment]
Thank You! Ran the code that fixed the issue - 

1 - Time Stamp does not seem to be updating – its when the script starts
Update 2023-10-02 – Same issue

2 - Column H currently – needs to be first column so vlookup can happen
Update 2023-10-02 – Perfect Thank You! 

3 - lower count and upper count does not seem to be updating
Update 2023-10-02 – Pending Code Update

4 - TOTAL_VOLUME does not work for some values, we are getting examples such as 8.45 Volume doesn’t seem to be correct

Update 2023-10-02 – Pending Code Update

**Comment by mxchinegod** [comment]
I believe 1 and 3 should both be fixed in https://github.com/DylanAlloy/tda-sheets/commit/3f8f224047dfcafd293e132bf931e30aa66eed92
